### ISSUE TITLE
Modelo de datos en JDL-Studio

### ISSUE THREAD

**Issue by jperezdelafuente** [taxy4fun/boot-cantaloupe#7]
Completar modelo de datos con la herramienta [JDL-Studio](https://jhipster.github.io/jdl-studio/), con el [código disponible](https://github.com/butcherless/boot-cantaloupe/blob/master/docs/dataModel-jdl.jh)

**Comment by jperezdelafuente** [comment]
![jhipster-jdl](https://user-images.githubusercontent.com/9991172/27005623-79c3a140-4e22-11e7-97f9-fb064e98a854.png)

**Comment by butcherless** [comment]
Se da por iniciado el modelo de dominio.
